### ISSUE TITLE
The request model: prometheus-eval/prometheus-7b-v2.0 does not exist!

### ISSUE THREAD

**Issue by HaoquanZhang** [AkariAsai/ScholarQABench#5]
Terminal output as follow

`python scripts/prometheus_eval.py \
    --batch_process_dir data/scholarqa_cs/src_answers \
    --output_path output/prometheus_cs \
    --rubric_path rubrics/prometheus_rubrics_v8.json \
    --instruction "Answer the question related to the most recent scientific literature." \
    --model prometheus-eval/prometheus-7b-v2.0 \
    --load_vllm \
    --top_n 10 \
    -f data/scholar_multi/human_answers.json \
    --aspects organization coverage
/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/_distutils_hack/__init__.py:54: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Downloading Model to directory: /mnt/workspace/.cache/modelscope/hub/prometheus-eval/prometheus-7b-v2.0
2024-12-25 19:40:39,405 - modelscope - ERROR - The request model: prometheus-eval/prometheus-7b-v2.0 does not exist!
Traceback (most recent call last):
  File "/cpfs01/user/zhanghaoquan/ScholarQABench/scripts/prometheus_eval.py", line 364, in <module>
    main(args)
  File "/cpfs01/user/zhanghaoquan/ScholarQABench/scripts/prometheus_eval.py", line 239, in main
    model = LLM(args.model, 
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 178, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 554, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 844, in create_engine_config
    model_config = self.create_model_config()
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 782, in create_model_config
    return ModelConfig(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/vllm/config.py", line 180, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision,
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 120, in get_config
    config = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/modelscope/utils/hf_util.py", line 335, in from_pretrained
    model_dir = snapshot_download(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 90, in snapshot_download
    return _snapshot_download(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 238, in _snapshot_download
    revision_detail = _api.get_valid_revision_detail(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/modelscope/hub/api.py", line 558, in get_valid_revision_detail
    all_branches_detail, all_tags_detail = self.get_model_branches_and_tags_details(
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/modelscope/hub/api.py", line 643, in get_model_branches_and_tags_details
    handle_http_response(r, logger, cookies, model_id)
  File "/root/miniconda3/envs/sb_env/lib/python3.10/site-packages/modelscope/hub/errors.py", line 122, in handle_http_response
    raise HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: The request model: prometheus-eval/prometheus-7b-v2.0 does not exist!`

**Comment by AkariAsai** [comment]
Hi, sorry for my late response! It seems that the error happens when you try to download the [prometheus-eval/prometheus-7b-v2.0](https://huggingface.co/prometheus-eval/prometheus-7b-v2.0) model. Could you double-check your HTTP connection on your server as well as the huggingface hub version?
